# Generated by Django 4.0.2 on 2022-07-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_oos'),
        ('sales', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.productsize', verbose_name='Size'),
        ),
    ]
