# Generated by Django 4.0.2 on 2022-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='returns_html',
            field=models.TextField(blank=True, null=True, verbose_name='Returns Policy'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='size_guide_html',
            field=models.TextField(blank=True, null=True, verbose_name='Size Guide'),
        ),
    ]
