# Generated by Django 4.0.2 on 2022-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shopsetting_returns_html_shopsetting_size_guide_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
