# Generated by Django 4.0.2 on 2022-06-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_supplieritem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_oos',
            field=models.BooleanField(default=False, verbose_name='Is out of stock'),
        ),
    ]
