# Generated by Django 4.0.2 on 2022-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieritem',
            name='url',
            field=models.URLField(blank=True, max_length=900, null=True, verbose_name='Supplier url'),
        ),
    ]
