# Generated by Django 4.0.2 on 2022-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_supplieritem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieritem',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier category'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='item_sn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item serial number'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='name',
            field=models.CharField(default='New supplier order', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID'),
        ),
    ]
