# Generated by Django 4.0.2 on 2022-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_supplieritem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Recommend 99', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_item_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Item identifier'),
        ),
    ]
