# Generated by Django 4.0.2 on 2022-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_name_alter_product_supplier_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
