# Generated by Django 4.0.2 on 2022-08-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_meta_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
