# Generated by Django 4.0.2 on 2022-10-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='rate',
            field=models.FloatField(default=1.0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
