# Generated by Django 4.0.2 on 2022-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_supplierorder_rate_alter_supplieritem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate'),
        ),
    ]
