# Generated by Django 4.1.5 on 2023-01-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_supplierorder_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.productimage', verbose_name='Cover'),
        ),
    ]
